#ifndef __VARLIST_H__
#define __VARLIST_H__

#define RC_MODE_STATIC 0
#define RC_MODE_VARIABLE 10
#define RC_MODE_VARIABLE_OPPOSITE 11

#define RC_BLICK_MODE_NONE 0
#define RC_BLICK_MODE_SIMPLE 1
#define RC_BLICK_MODE_PHASE 2

#define RC_FALSE 0
#define RC_TRUE 1

int RC_RGB1_MODE = RC_MODE_VARIABLE;
int RC_RGB1_DELAY = 10;
int RC_RGB1_THREAD_RUN = RC_FALSE;
uint32_t RC_RGB1_COLOUR = 0;
pthread_t RC_RGB1_THREAD;
int RC_RGB1_BLICK_MODE = RC_BLICK_MODE_NONE;
int RC_RGB1_BLICK_LIGHT = 1000;
int RC_RGB1_BLICK_DARK = 500;
int RC_RGB1_BLICK_PHASE = 0;

int RC_RGB2_MODE = RC_MODE_STATIC;
int RC_RGB2_DELAY = 10;
int RC_RGB2_THREAD_RUN = RC_FALSE;
uint32_t RC_RGB2_COLOUR = 0b00000000000000000000000011111111;
pthread_t RC_RGB2_THREAD;
int RC_RGB2_BLICK_MODE = RC_BLICK_MODE_SIMPLE;
int RC_RGB2_BLICK_LIGHT = 1000;
int RC_RGB2_BLICK_DARK = 500;
int RC_RGB2_BLICK_PHASE = 0;

char* RC_STATUS = " ";

#define RC_SERVER "cvut.skodaj.cz"
#define RC_SERVER_CONNECT "/apo/api/connect.php"
#define RC_SERVER_UPDATE_REMOTE "/apo/api/enable.php"
#define RC_SERVER_GET_CONFIG "/apo/api/config.php"
#define RC_SERVER_DISPLAY "http://cvut.skodaj.cz/apo"

#define SYS_INPUT_DELAY 200
#define SYS_REMOTE_DELAY 1000




#endif // !__VARLIST_H__
